import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const pertemuanCategories = Array.from({ length: 1 }, (_, i) => ({
  type: 'category',
  label: `Pertemuan ${i + 1}`,
  items: [
    {
      type: 'autogenerated',
      dirName: `materi/pertemuan${i + 1}`,
    },
  ],
}));

const sidebars: SidebarsConfig = {
  materiSidebar: [
    'materi/intro',
    ...pertemuanCategories
  ]
};

export default sidebars;
